version: 2.1

jobs:
  build_and_test:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python -m pytest

  build_and_push:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: |
            DOCKER_TAG=$(echo "${CIRCLE_SHA1}" | cut -c1-12)
            docker build -t nkondaboina/myapp:$DOCKER_TAG .

      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "Mywiz@rd360@123" | docker login --username "nkondaboina" --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push nkondaboina/myapp:$DOCKER_TAG

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push:
          filters:
            branches:
              only: main