version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout

      - run:
          name: "Install Dependencies"
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: "Run Tests"
          command: pytest

      - setup_remote_docker

      - run:
          name: "Build Docker Image"
          command: |
            docker build -t nkondaboina/sparse_recommender:latest .

      - run:
          name: "Push Docker Image"
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push nkondaboina/sparse_recommender:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
